//! Deterministic generator and drift checker for the built-in model catalog.

const std = @import("std");
const catalog = @import("catalog");
const model = catalog.model_types;

const max_document_bytes = 1024 * 1024;

const Source = struct {
    version: u32,
    updated_at: []const u8,
    entries: []const SourceEntry,
};

const SourceEntry = struct {
    provider_name: []const u8,
    id: []const u8,
    aliases: []const []const u8 = &.{},
    source_url: []const u8,
    deprecation: ?catalog.Deprecation = null,
    limits: catalog.Limits = .{},
    profile: SourceProfile,
};

const SourceProfile = struct {
    supports_tools: bool = false,
    supports_parallel_tool_calls: bool = false,
    supports_json_schema_output: bool = false,
    supports_json_object_output: bool = false,
    supports_system_messages: bool = false,
    supports_thinking: bool = false,
    supports_streaming: bool = false,
    supports_temperature: bool = false,
    supports_max_tokens: bool = false,
    supports_stop_sequences: bool = false,
    supports_seed: bool = false,
    supports_top_p: bool = false,
    supports_top_k: bool = false,
    supports_presence_penalty: bool = false,
    supports_frequency_penalty: bool = false,
    supports_logprobs: bool = false,
    supports_tool_choice: bool = false,
    supports_parallel_tool_call_setting: bool = false,
    supports_thinking_budget: bool = false,
    supports_truncation: bool = false,
    supports_request_headers: bool = false,
    supports_idempotency_key: bool = false,
    extra_body_kind: ?model.ExtraBodyKind = null,
    reasoning_efforts: []const model.ReasoningEffort = &.{},
    service_tiers: []const model.ServiceTier = &.{},
    builtin_tools: []const model.BuiltinToolKind = &.{},
    content_types: []const model.ContentType = &.{},
};

pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len != 4) return error.InvalidArguments;
    const source = try std.Io.Dir.cwd().readFileAlloc(
        init.io,
        args[2],
        init.gpa,
        .limited(max_document_bytes),
    );
    defer init.gpa.free(source);
    const generated = try generate(init.gpa, source);
    defer init.gpa.free(generated);

    if (std.mem.eql(u8, args[1], "check")) {
        const current = try std.Io.Dir.cwd().readFileAlloc(
            init.io,
            args[3],
            init.gpa,
            .limited(max_document_bytes),
        );
        defer init.gpa.free(current);
        if (!std.mem.eql(u8, generated, current)) return error.GeneratedSnapshotOutOfDate;
    } else if (std.mem.eql(u8, args[1], "update")) {
        var atomic = try std.Io.Dir.cwd().createFileAtomic(init.io, args[3], .{
            .make_path = true,
            .replace = true,
        });
        defer atomic.deinit(init.io);
        var buffer: [4096]u8 = undefined;
        var writer = atomic.file.writer(init.io, &buffer);
        try writer.interface.writeAll(generated);
        try writer.interface.flush();
        try atomic.file.sync(init.io);
        try atomic.replace(init.io);
    } else {
        return error.InvalidArguments;
    }
}

fn generate(allocator: std.mem.Allocator, source_text: []const u8) ![]u8 {
    return generateInner(allocator, source_text) catch |failure| switch (failure) {
        error.WriteFailed => error.OutOfMemory,
        else => |other| other,
    };
}

fn generateInner(allocator: std.mem.Allocator, source_text: []const u8) ![]u8 {
    const parsed = try std.json.parseFromSlice(Source, allocator, source_text, .{
        .allocate = .alloc_always,
        .ignore_unknown_fields = false,
        .max_value_len = max_document_bytes,
    });
    defer parsed.deinit();
    const source = parsed.value;
    try validateSource(allocator, source);

    var output: std.Io.Writer.Allocating = .init(allocator);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll(
        \\//! Generated by `zig build update-model-catalog`; do not edit directly.
        \\
        \\const std = @import("std");
        \\const catalog = @import("model_catalog.zig");
        \\const model = @import("model.zig");
        \\
    );
    try writer.print("pub const version: u32 = {};\n", .{source.version});
    try writer.print("pub const updated_at = \"{f}\";\n\n", .{std.zig.fmtString(source.updated_at)});
    try writer.writeAll("pub const entries = [_]catalog.Entry{\n");
    for (source.entries) |entry| try writeEntry(writer, entry);
    try writer.writeAll(
        \\};
        \\
        \\pub const value = catalog.Catalog{ .entries = &entries };
        \\
        \\test "generated model catalog is valid and resolvable" {
        \\    try value.validate();
        \\    try std.testing.expect(entries.len > 0);
        \\    for (entries) |entry| {
        \\        const resolved = value.resolve(entry.provider_name, entry.id).?;
        \\        try std.testing.expectEqualStrings(entry.id, resolved.canonicalId());
        \\        try std.testing.expect(entry.source_url != null);
        \\        try std.testing.expect(entry.profile != null);
        \\    }
        \\}
        \\
    );
    return output.toOwnedSlice();
}

fn validateSource(allocator: std.mem.Allocator, source: Source) !void {
    if (source.version != 1 or !validDate(source.updated_at) or source.entries.len == 0)
        return error.InvalidModelCatalogSource;
    var entries = try allocator.alloc(catalog.Entry, source.entries.len);
    defer allocator.free(entries);
    for (source.entries, 0..) |entry, index| {
        if (!std.mem.startsWith(u8, entry.source_url, "https://") or
            entry.source_url.len == "https://".len)
            return error.InvalidModelCatalogSource;
        if (index > 0 and compareEntry(source.entries[index - 1], entry) != .lt)
            return error.InvalidModelCatalogSource;
        try validateOrderedStrings(entry.aliases);
        try validateOrderedEnums(model.ReasoningEffort, entry.profile.reasoning_efforts);
        try validateOrderedEnums(model.ServiceTier, entry.profile.service_tiers);
        try validateOrderedEnums(model.BuiltinToolKind, entry.profile.builtin_tools);
        try validateOrderedEnums(model.ContentType, entry.profile.content_types);
        entries[index] = .{
            .provider_name = entry.provider_name,
            .id = entry.id,
            .aliases = entry.aliases,
            .source_url = entry.source_url,
            .deprecation = entry.deprecation,
            .limits = entry.limits,
            .profile = profileFromSource(entry.profile),
        };
    }
    _ = catalog.Catalog.init(entries) catch return error.InvalidModelCatalogSource;
}

fn compareEntry(left: SourceEntry, right: SourceEntry) std.math.Order {
    const provider_order = std.mem.order(u8, left.provider_name, right.provider_name);
    if (provider_order != .eq) return provider_order;
    return std.mem.order(u8, left.id, right.id);
}

fn validateOrderedStrings(values: []const []const u8) !void {
    for (values, 0..) |value, index| {
        if (value.len == 0) return error.InvalidModelCatalogSource;
        if (index > 0 and std.mem.order(u8, values[index - 1], value) != .lt)
            return error.InvalidModelCatalogSource;
    }
}

fn validateOrderedEnums(comptime T: type, values: []const T) !void {
    for (values, 0..) |value, index| {
        if (index > 0 and @intFromEnum(values[index - 1]) >= @intFromEnum(value))
            return error.InvalidModelCatalogSource;
    }
}

fn validDate(value: []const u8) bool {
    if (value.len != 10 or value[4] != '-' or value[7] != '-') return false;
    for (value, 0..) |byte, index| {
        if (index == 4 or index == 7) continue;
        if (!std.ascii.isDigit(byte)) return false;
    }
    const year = (@as(u16, value[0] - '0') * 1000) +
        (@as(u16, value[1] - '0') * 100) +
        (@as(u16, value[2] - '0') * 10) + value[3] - '0';
    const month = (@as(u8, value[5] - '0') * 10) + value[6] - '0';
    const day = (@as(u8, value[8] - '0') * 10) + value[9] - '0';
    if (year == 0 or month == 0 or month > 12 or day == 0) return false;
    const leap = @mod(year, 4) == 0 and (@mod(year, 100) != 0 or @mod(year, 400) == 0);
    const maximum_day: u8 = switch (month) {
        2 => if (leap) 29 else 28,
        4, 6, 9, 11 => 30,
        else => 31,
    };
    return day <= maximum_day;
}

fn profileFromSource(source: SourceProfile) model.ModelProfile {
    return .{
        .supports_tools = source.supports_tools,
        .supports_parallel_tool_calls = source.supports_parallel_tool_calls,
        .supports_json_schema_output = source.supports_json_schema_output,
        .supports_json_object_output = source.supports_json_object_output,
        .supports_system_messages = source.supports_system_messages,
        .supports_thinking = source.supports_thinking,
        .supports_streaming = source.supports_streaming,
        .supports_temperature = source.supports_temperature,
        .supports_max_tokens = source.supports_max_tokens,
        .supports_stop_sequences = source.supports_stop_sequences,
        .supports_seed = source.supports_seed,
        .supports_top_p = source.supports_top_p,
        .supports_top_k = source.supports_top_k,
        .supports_presence_penalty = source.supports_presence_penalty,
        .supports_frequency_penalty = source.supports_frequency_penalty,
        .supports_logprobs = source.supports_logprobs,
        .supports_tool_choice = source.supports_tool_choice,
        .supports_parallel_tool_call_setting = source.supports_parallel_tool_call_setting,
        .supports_thinking_budget = source.supports_thinking_budget,
        .supports_truncation = source.supports_truncation,
        .supports_request_headers = source.supports_request_headers,
        .supports_idempotency_key = source.supports_idempotency_key,
        .extra_body_kind = source.extra_body_kind,
        .reasoning_efforts = model.ModelProfile.ReasoningEffortSet.initMany(source.reasoning_efforts),
        .service_tiers = model.ModelProfile.ServiceTierSet.initMany(source.service_tiers),
        .builtin_tools = model.ModelProfile.BuiltinToolSet.initMany(source.builtin_tools),
        .content_types = model.ModelProfile.ContentTypeSet.initMany(source.content_types),
    };
}

fn writeEntry(writer: *std.Io.Writer, entry: SourceEntry) !void {
    try writer.print(
        "    .{{\n        .provider_name = \"{f}\",\n        .id = \"{f}\",\n",
        .{ std.zig.fmtString(entry.provider_name), std.zig.fmtString(entry.id) },
    );
    try writer.writeAll("        .aliases = &.{");
    if (entry.aliases.len > 1) try writer.writeByte(' ');
    for (entry.aliases, 0..) |alias, index| {
        if (index > 0) try writer.writeAll(", ");
        try writer.print("\"{f}\"", .{std.zig.fmtString(alias)});
    }
    if (entry.aliases.len > 1) try writer.writeByte(' ');
    try writer.writeAll("},\n");
    try writer.print("        .source_url = \"{f}\",\n", .{std.zig.fmtString(entry.source_url)});
    if (entry.deprecation) |deprecation| try writeDeprecation(writer, deprecation);
    try writer.writeAll("        .limits = .{ .context_window_tokens = ");
    try writeOptionalInteger(writer, entry.limits.context_window_tokens);
    try writer.writeAll(", .max_output_tokens = ");
    try writeOptionalInteger(writer, entry.limits.max_output_tokens);
    try writer.writeAll(" },\n");
    try writeProfile(writer, entry.profile);
    try writer.writeAll("    },\n");
}

fn writeDeprecation(writer: *std.Io.Writer, deprecation: catalog.Deprecation) !void {
    try writer.writeAll("        .deprecation = .{\n");
    if (deprecation.since) |value|
        try writer.print("            .since = \"{f}\",\n", .{std.zig.fmtString(value)});
    if (deprecation.sunset) |value|
        try writer.print("            .sunset = \"{f}\",\n", .{std.zig.fmtString(value)});
    if (deprecation.replacement) |value|
        try writer.print("            .replacement = \"{f}\",\n", .{std.zig.fmtString(value)});
    try writer.writeAll("        },\n");
}

fn writeProfile(writer: *std.Io.Writer, profile: SourceProfile) !void {
    try writer.writeAll("        .profile = .{\n");
    inline for (profile_boolean_fields) |field| {
        try writer.print("            .{s} = {},\n", .{ field, @field(profile, field) });
    }
    if (profile.extra_body_kind) |kind|
        try writer.print("            .extra_body_kind = .{s},\n", .{@tagName(kind)});
    try writeEnumSet(writer, "reasoning_efforts", profile.reasoning_efforts);
    try writeEnumSet(writer, "service_tiers", profile.service_tiers);
    try writeEnumSet(writer, "builtin_tools", profile.builtin_tools);
    try writeEnumSet(writer, "content_types", profile.content_types);
    try writer.writeAll("        },\n");
}

const profile_boolean_fields = .{
    "supports_tools",
    "supports_parallel_tool_calls",
    "supports_json_schema_output",
    "supports_json_object_output",
    "supports_system_messages",
    "supports_thinking",
    "supports_streaming",
    "supports_temperature",
    "supports_max_tokens",
    "supports_stop_sequences",
    "supports_seed",
    "supports_top_p",
    "supports_top_k",
    "supports_presence_penalty",
    "supports_frequency_penalty",
    "supports_logprobs",
    "supports_tool_choice",
    "supports_parallel_tool_call_setting",
    "supports_thinking_budget",
    "supports_truncation",
    "supports_request_headers",
    "supports_idempotency_key",
};

fn writeEnumSet(writer: *std.Io.Writer, name: []const u8, values: anytype) !void {
    try writer.print("            .{s} = model.ModelProfile.", .{name});
    const set_name = if (std.mem.eql(u8, name, "reasoning_efforts"))
        "ReasoningEffortSet"
    else if (std.mem.eql(u8, name, "service_tiers"))
        "ServiceTierSet"
    else if (std.mem.eql(u8, name, "builtin_tools"))
        "BuiltinToolSet"
    else
        "ContentTypeSet";
    try writer.print("{s}.initMany(&.{{", .{set_name});
    if (values.len > 1) try writer.writeByte(' ');
    for (values, 0..) |value, index| {
        if (index > 0) try writer.writeAll(", ");
        try writer.print(".{s}", .{@tagName(value)});
    }
    if (values.len > 1) try writer.writeByte(' ');
    try writer.writeAll("}),\n");
}

fn writeOptionalInteger(writer: *std.Io.Writer, value: ?u64) !void {
    if (value) |integer| try writer.print("{}", .{integer}) else try writer.writeAll("null");
}

test "generator is deterministic and validates source ordering" {
    const fixture =
        \\{"version":1,"updated_at":"2026-08-16","entries":[{"provider_name":"test","id":"model","aliases":["alias"],"source_url":"https://example.test/model","limits":{"context_window_tokens":10,"max_output_tokens":2},"profile":{"supports_tools":true,"reasoning_efforts":["low"]}}]}
    ;
    const first = try generate(std.testing.allocator, fixture);
    defer std.testing.allocator.free(first);
    const second = try generate(std.testing.allocator, fixture);
    defer std.testing.allocator.free(second);
    try std.testing.expectEqualStrings(first, second);
    try std.testing.expect(std.mem.indexOf(u8, first, ".supports_tools = true") != null);
    try std.testing.expect(std.mem.indexOf(u8, first, ".supports_temperature = false") != null);
    try std.testing.expect(std.mem.indexOf(u8, first, ".reasoning_efforts = model.ModelProfile.ReasoningEffortSet.initMany(&.{.low})") != null);

    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":2,\"updated_at\":\"2026-08-16\",\"entries\":[]}",
    ));
    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":1,\"updated_at\":\"bad\",\"entries\":[]}",
    ));
    try std.testing.expectError(error.InvalidModelCatalogSource, generate(
        std.testing.allocator,
        "{\"version\":1,\"updated_at\":\"2026-02-29\",\"entries\":[]}",
    ));
}

test "generator releases every allocation" {
    const fixture =
        \\{"version":1,"updated_at":"2026-08-16","entries":[{"provider_name":"test","id":"model","source_url":"https://example.test/model","profile":{}}]}
    ;
    try std.testing.checkAllAllocationFailures(std.testing.allocator, struct {
        fn exercise(allocator: std.mem.Allocator, source: []const u8) !void {
            const generated = try generate(allocator, source);
            defer allocator.free(generated);
        }
    }.exercise, .{fixture});
}
