//! Generated by `zig build update-model-catalog`; do not edit directly.

const std = @import("std");
const catalog = @import("model_catalog.zig");
const model = @import("model.zig");
pub const version: u32 = 1;
pub const updated_at = "2026-08-16";

pub const entries = [_]catalog.Entry{
    .{
        .provider_name = "anthropic",
        .id = "claude-sonnet-5",
        .aliases = &.{},
        .source_url = "https://platform.claude.com/docs/en/about-claude/models/whats-new-sonnet-5",
        .limits = .{ .context_window_tokens = 1000000, .max_output_tokens = 128000 },
        .profile = .{
            .supports_tools = true,
            .supports_parallel_tool_calls = true,
            .supports_json_schema_output = true,
            .supports_json_object_output = false,
            .supports_system_messages = true,
            .supports_thinking = true,
            .supports_streaming = true,
            .supports_temperature = false,
            .supports_max_tokens = true,
            .supports_stop_sequences = true,
            .supports_seed = false,
            .supports_top_p = false,
            .supports_top_k = false,
            .supports_presence_penalty = false,
            .supports_frequency_penalty = false,
            .supports_logprobs = false,
            .supports_tool_choice = true,
            .supports_parallel_tool_call_setting = true,
            .supports_thinking_budget = false,
            .supports_truncation = false,
            .supports_request_headers = true,
            .supports_idempotency_key = false,
            .extra_body_kind = .anthropic,
            .reasoning_efforts = model.ModelProfile.ReasoningEffortSet.initMany(&.{ .low, .medium, .high, .max }),
            .service_tiers = model.ModelProfile.ServiceTierSet.initMany(&.{}),
            .builtin_tools = model.ModelProfile.BuiltinToolSet.initMany(&.{ .web_search, .web_fetch }),
            .content_types = model.ModelProfile.ContentTypeSet.initMany(&.{ .image, .document, .thinking }),
        },
    },
    .{
        .provider_name = "gcp.gen_ai",
        .id = "gemini-3.6-flash",
        .aliases = &.{},
        .source_url = "https://ai.google.dev/gemini-api/docs/models/gemini-3.6-flash",
        .limits = .{ .context_window_tokens = 1048576, .max_output_tokens = 65536 },
        .profile = .{
            .supports_tools = true,
            .supports_parallel_tool_calls = true,
            .supports_json_schema_output = true,
            .supports_json_object_output = true,
            .supports_system_messages = true,
            .supports_thinking = true,
            .supports_streaming = true,
            .supports_temperature = true,
            .supports_max_tokens = true,
            .supports_stop_sequences = true,
            .supports_seed = true,
            .supports_top_p = true,
            .supports_top_k = true,
            .supports_presence_penalty = true,
            .supports_frequency_penalty = true,
            .supports_logprobs = true,
            .supports_tool_choice = true,
            .supports_parallel_tool_call_setting = false,
            .supports_thinking_budget = true,
            .supports_truncation = false,
            .supports_request_headers = true,
            .supports_idempotency_key = false,
            .extra_body_kind = .google,
            .reasoning_efforts = model.ModelProfile.ReasoningEffortSet.initMany(&.{ .minimal, .low, .medium, .high }),
            .service_tiers = model.ModelProfile.ServiceTierSet.initMany(&.{}),
            .builtin_tools = model.ModelProfile.BuiltinToolSet.initMany(&.{ .web_search, .web_fetch }),
            .content_types = model.ModelProfile.ContentTypeSet.initMany(&.{ .image, .audio, .video, .document, .binary, .thinking }),
        },
    },
    .{
        .provider_name = "openai",
        .id = "gpt-5.6-sol",
        .aliases = &.{"gpt-5.6"},
        .source_url = "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
        .limits = .{ .context_window_tokens = 1050000, .max_output_tokens = 128000 },
        .profile = .{
            .supports_tools = true,
            .supports_parallel_tool_calls = true,
            .supports_json_schema_output = true,
            .supports_json_object_output = true,
            .supports_system_messages = true,
            .supports_thinking = true,
            .supports_streaming = true,
            .supports_temperature = false,
            .supports_max_tokens = true,
            .supports_stop_sequences = false,
            .supports_seed = false,
            .supports_top_p = false,
            .supports_top_k = false,
            .supports_presence_penalty = false,
            .supports_frequency_penalty = false,
            .supports_logprobs = false,
            .supports_tool_choice = true,
            .supports_parallel_tool_call_setting = true,
            .supports_thinking_budget = false,
            .supports_truncation = true,
            .supports_request_headers = true,
            .supports_idempotency_key = false,
            .extra_body_kind = .openai,
            .reasoning_efforts = model.ModelProfile.ReasoningEffortSet.initMany(&.{ .none, .low, .medium, .high, .xhigh, .max }),
            .service_tiers = model.ModelProfile.ServiceTierSet.initMany(&.{}),
            .builtin_tools = model.ModelProfile.BuiltinToolSet.initMany(&.{.web_search}),
            .content_types = model.ModelProfile.ContentTypeSet.initMany(&.{ .image, .document, .binary }),
        },
    },
};

pub const value = catalog.Catalog{ .entries = &entries };

test "generated model catalog is valid and resolvable" {
    try value.validate();
    try std.testing.expect(entries.len > 0);
    for (entries) |entry| {
        const resolved = value.resolve(entry.provider_name, entry.id).?;
        try std.testing.expectEqualStrings(entry.id, resolved.canonicalId());
        try std.testing.expect(entry.source_url != null);
        try std.testing.expect(entry.profile != null);
    }
}
